name: "🐛 Bug report"
description: "Something is not working as expected"
labels: "bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of the problem you ran into, either as a code snippet or some form of code sandbox. If other steps are required to reproduce the faulty behaviour, please describe them here aswell.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System info
      description: Output of `npx envinfo --system --npmPackages '{@quintal/*,typescript}' --binaries`
      render: shell
      placeholder: System, npmPackages, Binaries
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used package manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
        - bun
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/quintalwebsolutions/quintal-oss/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/quintalwebsolutions/quintal-oss/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/quintalwebsolutions/quintal-oss/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Add labels with the names of the affected package(s) to this issue
          required: true
