name: "🚀 Feature request"
description: "Suggestion for new functionality"
labels: "feature"
body:
  - type: markdown
    attributes:
      value: Thanks for your interest in the project and taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: "Clear and concise description of the problem. Please make the reason and use cases as clear as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
      placeholder: As a developer using @quintal/... I want ... so that ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: The solution you have in mind that will solve the problem
      placeholder: "In ... we could provide ..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A description of any alternative solutions you've considered and why they do or don't suffice.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/quintalwebsolutions/quintal-oss/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/quintalwebsolutions/quintal-oss/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/quintalwebsolutions/quintal-oss/issues) that requests the same feature to avoid creating a duplicate.
          required: true
        - label: Add labels with the names of the affected package(s) to this issue.
          required: true
