name: Collect coverage from all packages

runs:
  using: composite
  steps:
    - name: Upload @quintal/test coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/test/.coverage/coverage-final.json
        flags: test
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload @quintal/config coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/config/.coverage/coverage-final.json
        flags: config
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload @quintal/environment coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/environment/.coverage/coverage-final.json
        flags: environment
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload @quintal/form-engine-react coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/form-engine-react/.coverage/coverage-final.json
        flags: form-engine-react
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload @quintal/monads coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/monads/.coverage/coverage-final.json
        flags: monads
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload @quintal/table-engine-react coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        file: ./packages/table-engine-react/.coverage/coverage-final.json
        flags: table-engine-react
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
