module.exports = {
  $schema: "https://json.schemastore.org/prettierrc",
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: "consistent",
  jsxSingleQuote: false,
  trailingComma: "all",
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: "always",
  proseWrap: "always",
  htmlWhitespaceSensitivity: "strict",
  endOfLine: "lf",
  singleAttributePerLine: false,
};
