name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint:check

      - name: Test
        run: pnpm test

      - name: Collect test coverage
        uses: "./.github/actions/collect_coverage"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
