name: Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml
          fetch-depth: 0

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
