name: Pull Request Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labeler.yml
          fetch-depth: 0

      - name: Run labeler
        uses: actions/labeler@v5
        with:
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
